name: Build SFOS 4.6

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: coderus/sailfishos-platform-sdk-aarch64:4.6.0.13

    steps:
    - name: Setup and Check Environment
      run: |
        whoami
        pwd
        ls -la /home/mersdk
        
    - name: Manual Checkout
      run: |
        cd /home/mersdk
        git clone https://github.com/conradhuebler/harbour-tidalplayer.git
        cd harbour-tidalplayer
        git submodule update --init --recursive
        ls -la
    
    - name: Build noarch
      working-directory: /home/mersdk/harbour-tidalplayer
      env:
        HOME: /home/mersdk
      run: |
        pwd
        mb2 -t SailfishOS-4.6.0.13-aarch64 build
        
    - name: Rename RPM to noarch
      run: |
        cd /home/mersdk/harbour-tidalplayer/RPMS/
        mv harbour-tidalplayer-*-1.aarch64.rpm harbour-tidalplayer-master-1.noarch.rpm
        ls -la
      
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: rpms
        path: /home/mersdk/harbour-tidalplayer/RPMS/harbour-tidalplayer-master-1.noarch.rpm

    - name: Create/Update Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: nightly
        name: Nightly Build
        files: /home/mersdk/harbour-tidalplayer/RPMS/harbour-tidalplayer-master-1.noarch.rpm
        prerelease: true
        body: Automated nightly build
        token: ${{ secrets.GITHUB_TOKEN }}
        replace_artifacts: true
