name: Build SFOS 4.2

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: coderus/sailfishos-platform-sdk:4.2.0.21

    steps:
    - uses: actions/checkout@v2
    
    - name: Build for aarch64
      run: mb2 -t SailfishOS-4.2.0.21-aarch64 build
      
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: rpms
        path: RPMS/*.rpm

    - name: Create/Update Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: nightly
        name: Nightly Build
        files: RPMS/*.rpm
        prerelease: true
        body: Automated nightly build
        token: ${{ secrets.GITHUB_TOKEN }}
        replace_artifacts: true

