# .github/workflows/sailfish-build.yml
name: Sailfish OS Package Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: coderus/sailfishos-platform-sdk:4.4.0.58
      options: --privileged

    steps:
    - uses: actions/checkout@v4

    - name: Prepare build environment
      run: |
        mkdir -p ~/rpmbuild/SOURCES
        mkdir -p ~/rpmbuild/SPECS
        cp rpm/harbour-tidalplayer.spec ~/rpmbuild/SPECS/
        cp rpm/harbour-tidalplayer.yaml ~/rpmbuild/SPECS/

    - name: Create source tarball
      run: |
        VERSION=$(grep "Version:" rpm/harbour-tidalplayer.yaml | cut -d':' -f2 | tr -d ' ')
        tar --transform "s,^,harbour-tidalplayer-$VERSION/," -czf ~/rpmbuild/SOURCES/harbour-tidalplayer-$VERSION.tar.gz *

    - name: Build RPM package
      run: |
        cd ~/rpmbuild/SPECS
        mb2 -t SailfishOS-4.4.0.58 -s harbour-tidalplayer.spec build

    - name: Upload RPM artifacts
      uses: actions/upload-artifact@v4
      with:
        name: harbour-tidalplayer-rpm
        path: ~/rpmbuild/RPMS/**/*.rpm
        if-no-files-found: error

    # Optional: Release erstellen wenn getaggt
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ~/rpmbuild/RPMS/**/*.rpm
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
