name: Build SFOS 4.6

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: coderus/sailfishos-platform-sdk-aarch64:4.6.0.13

    steps:
    - name: Setup and Check Environment
      run: |
        whoami
        pwd
        ls -la /home/mersdk
        
    - name: Manual Checkout
      run: |
        cd /home/mersdk
        git clone https://github.com/conradhuebler/harbour-tidalplayer.git
        cd harbour-tidalplayer
        git submodule update --init --recursive
        ls -la
    
    - name: Build noarch
      working-directory: /home/mersdk/harbour-tidalplayer
      env:
        HOME: /home/mersdk
      run: |
        pwd
        mb2 -t SailfishOS-4.6.0.13-aarch64 build
        
    - name: Rename RPM to noarch
      run: |
        cd /home/mersdk/harbour-tidalplayer/RPMS/
        mv harbour-tidalplayer-*-1.aarch64.rpm harbour-tidalplayer-master-1.noarch.rpm
        ls -la

    - name: Install curl
      run: |
        sudo zypper --non-interactive install curl


    - name: Get Release ID
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        RELEASE_ID=$(curl -H "Authorization: token $GITHUB_TOKEN" \
                         -H "Accept: application/vnd.github.v3+json" \
                         https://api.github.com/repos/conradhuebler/harbour-tidalplayer/releases/tags/master | \
                    grep -o '"id": [0-9]*' | head -1 | cut -d' ' -f2)
        echo "RELEASE_ID=$RELEASE_ID" >> $GITHUB_ENV

    - name: Upload to Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd /home/mersdk/harbour-tidalplayer/RPMS/
        curl -X POST \
          -H "Authorization: token $GITHUB_TOKEN" \
          -H "Content-Type: application/x-rpm" \
          --data-binary @harbour-tidalplayer-master-1.noarch.rpm \
          "https://uploads.github.com/repos/conradhuebler/harbour-tidalplayer/releases/${RELEASE_ID}/assets?name=harbour-tidalplayer-master-1.noarch.rpm"
